#Splash screen properties
#Mon Sep 07 00:35:30 GMT-03:00 2026
background=0x389E82
bar=0xFFFFFF
barBackground=0x389E82
barBorder=0x389E82
enabled=true
font=0x08151E
fontTexture=textures/font/ascii.png
forgeTexture=fml\:textures/gui/cat.gif
logoOffset=0
memoryGood=0xFFFFFF
memoryLow=0x1D5E5C
memoryWarn=0xE6E84A
resourcePackPath=resources
rotate=false
showMemory=true
